/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_diegovarela;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Examen extends javax.swing.JFrame {

    ArrayList<Persona> personas = new ArrayList();
    ArrayList<Objetos> objetos = new ArrayList();

    /**
     * Creates new form Examen
     */
    public Examen() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Gerente = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rb_sucursal = new javax.swing.JRadioButton();
        rb_planta = new javax.swing.JRadioButton();
        tf_usuario = new javax.swing.JTextField();
        tf_contraseña = new javax.swing.JTextField();
        jb_agregargerente = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Personal = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_ocupacion = new javax.swing.JTextField();
        tf_horario = new javax.swing.JTextField();
        tf_sueldo = new javax.swing.JTextField();
        jb_agregarpersonal = new javax.swing.JButton();
        sp_semanas = new javax.swing.JSpinner();
        Ropa = new javax.swing.JFrame();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tf_tallaropa = new javax.swing.JTextField();
        tf_telaropa = new javax.swing.JTextField();
        tf_paisropa = new javax.swing.JTextField();
        jb_agregarropa = new javax.swing.JButton();
        Zapatos = new javax.swing.JFrame();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        sp_calidadzapatos = new javax.swing.JSpinner();
        tf_tallazapatos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new javax.swing.JTextArea();
        jb_agregarzapatos = new javax.swing.JButton();
        Hogar = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_descripcionhogar = new javax.swing.JTextArea();
        jb_agregarhogar = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        sp_garantiahogar = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_instruccioneshogar = new javax.swing.JTextArea();
        Agregar_panel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_personas = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_objetos = new javax.swing.JTable();
        jb_listarpersonas = new javax.swing.JButton();
        jb_listarobjetos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cb_eliminarpers = new javax.swing.JComboBox<>();
        cb_elimobje = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jb_eliminarpers = new javax.swing.JButton();
        jb_eliminarobjetos = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sp_id = new javax.swing.JSpinner();
        tf_nombre = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        rb_femeninno = new javax.swing.JRadioButton();
        rb_masculino = new javax.swing.JRadioButton();
        rb_casado = new javax.swing.JRadioButton();
        rb_soltero = new javax.swing.JRadioButton();
        tf_altura = new javax.swing.JTextField();
        tf_peso = new javax.swing.JTextField();
        rb_gerente = new javax.swing.JRadioButton();
        rb_personal = new javax.swing.JRadioButton();
        jb_agregarpersona = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_tamaño = new javax.swing.JTextField();
        tf_calidado = new javax.swing.JTextField();
        tf_marca = new javax.swing.JTextField();
        cb_persona = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        rb_ropa = new javax.swing.JRadioButton();
        rb_hogar = new javax.swing.JRadioButton();
        rb_zapatos = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_descripciono = new javax.swing.JTextArea();

        jLabel11.setText("Usuario:");

        jLabel12.setText("Contraseña:");

        jLabel13.setText("Cargo:");

        rb_sucursal.setText("Gerente sucursal");

        rb_planta.setText("Gerente de planta");

        jb_agregargerente.setText("Agregar");
        jb_agregargerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregargerenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout GerenteLayout = new javax.swing.GroupLayout(Gerente.getContentPane());
        Gerente.getContentPane().setLayout(GerenteLayout);
        GerenteLayout.setHorizontalGroup(
            GerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GerenteLayout.createSequentialGroup()
                .addGroup(GerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GerenteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(GerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GerenteLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_sucursal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_planta))
                            .addGroup(GerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GerenteLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_usuario))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GerenteLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(GerenteLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jb_agregargerente)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        GerenteLayout.setVerticalGroup(
            GerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GerenteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(GerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(GerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GerenteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GerenteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rb_sucursal)
                    .addComponent(rb_planta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jb_agregargerente)
                .addContainerGap())
        );

        jLabel14.setText("Ocupacion:");

        jLabel15.setText("Horario:");

        jLabel16.setText("Semanas trabajando:");

        jLabel17.setText("Sueldo:");

        jb_agregarpersonal.setText("Agregar personal");
        jb_agregarpersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarpersonalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PersonalLayout = new javax.swing.GroupLayout(Personal.getContentPane());
        Personal.getContentPane().setLayout(PersonalLayout);
        PersonalLayout.setHorizontalGroup(
            PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalLayout.createSequentialGroup()
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonalLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PersonalLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PersonalLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PersonalLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sp_semanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PersonalLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PersonalLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jb_agregarpersonal)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        PersonalLayout.setVerticalGroup(
            PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(sp_semanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_agregarpersonal)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel25.setText("Talla:");

        jLabel26.setText("Tela:");

        jLabel27.setText("Pais:");

        jb_agregarropa.setText("Agregar ropa");
        jb_agregarropa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarropaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RopaLayout = new javax.swing.GroupLayout(Ropa.getContentPane());
        Ropa.getContentPane().setLayout(RopaLayout);
        RopaLayout.setHorizontalGroup(
            RopaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RopaLayout.createSequentialGroup()
                .addGroup(RopaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RopaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(RopaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(RopaLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tallaropa))
                            .addGroup(RopaLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_telaropa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RopaLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_paisropa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(RopaLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jb_agregarropa)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        RopaLayout.setVerticalGroup(
            RopaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RopaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(RopaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_tallaropa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(RopaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_telaropa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(RopaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_paisropa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_agregarropa)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel28.setText("Talla:");

        jLabel29.setText("Descripcion:");

        jLabel30.setText("Calidad:");

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_descripcion);

        jb_agregarzapatos.setText("Agregar zapatos");
        jb_agregarzapatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarzapatosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ZapatosLayout = new javax.swing.GroupLayout(Zapatos.getContentPane());
        Zapatos.getContentPane().setLayout(ZapatosLayout);
        ZapatosLayout.setHorizontalGroup(
            ZapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZapatosLayout.createSequentialGroup()
                .addGroup(ZapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ZapatosLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(ZapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ZapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_tallazapatos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_calidadzapatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ZapatosLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jb_agregarzapatos)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        ZapatosLayout.setVerticalGroup(
            ZapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZapatosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(ZapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ZapatosLayout.createSequentialGroup()
                        .addGroup(ZapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(tf_tallazapatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel29))
                    .addGroup(ZapatosLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(ZapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_calidadzapatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jb_agregarzapatos))
        );

        ta_descripcionhogar.setColumns(20);
        ta_descripcionhogar.setRows(5);
        jScrollPane2.setViewportView(ta_descripcionhogar);

        jb_agregarhogar.setText("Agregar hogar");
        jb_agregarhogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarhogarMouseClicked(evt);
            }
        });

        jLabel31.setText("Instruccciones:");

        jLabel32.setText("Descripcion:");

        jLabel33.setText("Garantia(meses):");

        ta_instruccioneshogar.setColumns(20);
        ta_instruccioneshogar.setRows(5);
        jScrollPane3.setViewportView(ta_instruccioneshogar);

        javax.swing.GroupLayout HogarLayout = new javax.swing.GroupLayout(Hogar.getContentPane());
        Hogar.getContentPane().setLayout(HogarLayout);
        HogarLayout.setHorizontalGroup(
            HogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HogarLayout.createSequentialGroup()
                .addGroup(HogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HogarLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(HogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(sp_garantiahogar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2)))
                    .addGroup(HogarLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jb_agregarhogar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HogarLayout.setVerticalGroup(
            HogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HogarLayout.createSequentialGroup()
                .addGroup(HogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HogarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel31))
                    .addGroup(HogarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(HogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HogarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel32)))
                .addGap(36, 36, 36)
                .addGroup(HogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_garantiahogar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addComponent(jb_agregarhogar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Agregar_panel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Agregar_panelStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        Agregar_panel.addTab("Modificar", jPanel2);

        jt_personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Sexo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jt_personas);

        jt_objetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Tamaño", "Calidad", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jt_objetos);

        jb_listarpersonas.setText("Listar personas");
        jb_listarpersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarpersonasMouseClicked(evt);
            }
        });

        jb_listarobjetos.setText("Listar objetos");
        jb_listarobjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarobjetosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jb_listarpersonas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_listarobjetos)
                .addGap(209, 209, 209))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_listarpersonas)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_listarobjetos)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        Agregar_panel.addTab("Listar", jPanel3);

        jLabel34.setText("Eliminar objetos");

        jLabel35.setText("Eliminar personas");

        jb_eliminarpers.setText("Eliminar personas");
        jb_eliminarpers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarpersMouseClicked(evt);
            }
        });

        jb_eliminarobjetos.setText("Eliminar objetos");
        jb_eliminarobjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarobjetosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(cb_eliminarpers, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_elimobje, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_eliminarpers)
                    .addComponent(jLabel35))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel34)
                        .addGap(113, 113, 113))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jb_eliminarobjetos)
                        .addContainerGap(90, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel34))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_eliminarpers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_elimobje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jb_eliminarpers))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jb_eliminarobjetos)))
                .addContainerGap(280, Short.MAX_VALUE))
        );

        Agregar_panel.addTab("Eliminar", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        Agregar_panel.addTab("Mensaje", jPanel5);

        jLabel1.setText("Agregar persona");

        jLabel2.setText("Agregar objeto");

        jLabel3.setText("Identificacion:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Edad:");

        jLabel6.setText("Sexo:");

        jLabel7.setText("Estado:");

        jLabel8.setText("Altura:");

        jLabel9.setText("Peso:");

        jLabel10.setText("Tipo de persona;");

        rb_femeninno.setText("F");

        rb_masculino.setText("M");

        rb_casado.setText("Casado");

        rb_soltero.setText("Soltero");
        rb_soltero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_solteroActionPerformed(evt);
            }
        });

        tf_peso.setText(" ");

        rb_gerente.setText("Gerente");

        rb_personal.setText("Personal");

        jb_agregarpersona.setText("Agregar persona");
        jb_agregarpersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarpersonaMouseClicked(evt);
            }
        });

        jLabel18.setText("Tamaño:");

        jLabel19.setText("Color:");

        jLabel20.setText("Calidad:");

        jLabel21.setText("Descripcion:");

        jLabel22.setText("Marca:");

        jLabel23.setText("Persona que lo ingreso:");

        jButton1.setText("Color");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Agregar Objeto");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel24.setText("Tipo:");

        rb_ropa.setText("Ropa");

        rb_hogar.setText("Hogar");

        rb_zapatos.setText("Zapatos");

        ta_descripciono.setColumns(20);
        ta_descripciono.setRows(5);
        jScrollPane4.setViewportView(ta_descripciono);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(102, 102, 102))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_gerente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_personal))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jb_agregarpersona)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cb_persona, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rb_ropa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rb_hogar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rb_zapatos)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jButton2)))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_femeninno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_masculino))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_casado)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_soltero))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sp_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_calidado))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(30, 30, 30)
                                    .addComponent(jButton1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sp_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rb_femeninno)
                            .addComponent(rb_masculino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rb_casado)
                            .addComponent(rb_soltero)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(tf_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(tf_calidado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(rb_gerente)
                            .addComponent(rb_personal))
                        .addGap(18, 18, 18)
                        .addComponent(jb_agregarpersona)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(rb_ropa)
                                .addComponent(rb_hogar)
                                .addComponent(rb_zapatos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(cb_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(46, 46, 46))))
        );

        Agregar_panel.addTab("Agregar", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(Agregar_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Agregar_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_solteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_solteroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_solteroActionPerformed

    private void jb_agregarpersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarpersonaMouseClicked
        // TODO add your handling code here:
        try {
            String cont = JOptionPane.showInputDialog("Ingrese la contraseña:");
            if (cont.equals("unitec1234")) {
                if (rb_gerente.isSelected()) {
                    Gerente.pack();
                    Gerente.setLocationRelativeTo(null);
                    Gerente.setVisible(true);
                } else {
                    Personal.pack();
                    Personal.setLocationRelativeTo(null);
                    Personal.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_agregarpersonaMouseClicked

    private void jb_agregarpersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarpersonalMouseClicked
        // TODO add your handling code here:
        try {
            String sexo = "";
            String estado = "";
            if (rb_femeninno.isSelected()) {
                sexo = "Femenino";
            } else if (rb_masculino.isSelected()) {
                sexo = "Masculino";
            }
            if (rb_soltero.isSelected()) {
                estado = "Soltero";
            } else if (rb_casado.isSelected()) {
                estado = "Casado";
            }
            Personal x = new Personal(tf_ocupacion.getText(), tf_horario.getText(), (int) sp_semanas.getValue(), Integer.parseInt(tf_sueldo.getText()), (int) sp_id.getValue(), tf_nombre.getText(), (int) sp_edad.getValue(), sexo, estado, Double.parseDouble(tf_altura.getText()), Double.parseDouble(tf_peso.getText()));
            personas.add(x);
            JOptionPane.showMessageDialog(null, "Se agrego con exito");
            personas.add(x);
            JOptionPane.showMessageDialog(null, "Se agrego con exito");
            DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_persona.getModel();
            dc.addElement(x);
            cb_persona.setModel(dc);
            Personal.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_agregarpersonalMouseClicked

    private void jb_agregargerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregargerenteMouseClicked
        // TODO add your handling code here:
        try {
            String sexo = "";
            String estado = "";
            String cargo = "";
            if (rb_femeninno.isSelected()) {
                sexo = "Femenino";
            } else if (rb_masculino.isSelected()) {
                sexo = "Masculino";
            }
            if (rb_soltero.isSelected()) {
                estado = "Soltero";
            } else if (rb_casado.isSelected()) {
                estado = "Casado";
            }
            if (rb_sucursal.isSelected()) {
                estado = "Gerente de sucursal";
            } else if (rb_planta.isSelected()) {
                estado = "Gerente de planta";
            }
            Gerente x = new Gerente(tf_usuario.getText(), tf_contraseña.getText(), cargo, (int) sp_id.getValue(), estado, (int) sp_edad.getValue(), sexo, estado, Double.parseDouble(tf_altura.getText()), Double.parseDouble(tf_peso.getText()));
            personas.add(x);
            JOptionPane.showMessageDialog(null, "Se agrego con exito");
            DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_persona.getModel();
            dc.addElement(x);
            cb_persona.setModel(dc);
            Gerente.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_agregargerenteMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
            String cont = JOptionPane.showInputDialog("Ingrese la contraseña:");
            if (cont.equals("unitec1234")) {
                if (rb_ropa.isSelected()) {
                    Ropa.pack();
                    Ropa.setLocationRelativeTo(null);
                    Ropa.setVisible(true);
                } else if (rb_zapatos.isSelected()) {
                    Zapatos.pack();
                    Zapatos.setLocationRelativeTo(null);
                    Zapatos.setVisible(true);
                } else if (rb_hogar.isSelected()) {
                    Hogar.pack();
                    Hogar.setLocationRelativeTo(null);
                    Hogar.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jb_agregarropaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarropaMouseClicked
        // TODO add your handling code here:
        try {
            objetos.add(new Ropa(tf_tallaropa.getText(), tf_telaropa.getText(), tf_paisropa.getText(), c, ta_descripciono.getText(), tf_marca.getText(), tf_tamaño.getText(), tf_calidado.getText(), (Persona) cb_persona.getSelectedItem()));
            JOptionPane.showMessageDialog(null, "Se agrego con exito");
            Ropa.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_agregarropaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        c = JColorChooser.showDialog(this, "Seleccione Color", Color.yellow);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_agregarzapatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarzapatosMouseClicked
        // TODO add your handling code here:
        try {
            objetos.add(new Zapatos(Integer.parseInt(tf_tallazapatos.getText()), ta_descripcion.getText(), (int) sp_calidadzapatos.getValue(), c, ta_descripciono.getText(), tf_marca.getText(), tf_tamaño.getText(), tf_calidado.getText(), (Persona) cb_persona.getSelectedItem()));
            JOptionPane.showMessageDialog(null, "Se agrego con exito");
            Zapatos.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_agregarzapatosMouseClicked

    private void jb_agregarhogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarhogarMouseClicked
        // TODO add your handling code here:
        try {
            objetos.add(new Hogar(ta_descripcionhogar.getText(), ta_instruccioneshogar.getText(), (int) sp_garantiahogar.getValue(), c, ta_descripciono.getText(), tf_marca.getText(), tf_tamaño.getText(), tf_calidado.getText(), (Persona) cb_persona.getSelectedItem()));
            JOptionPane.showMessageDialog(null, "Se agrego con exito");
            Hogar.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_agregarhogarMouseClicked

    private void jb_listarpersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarpersonasMouseClicked
        // TODO add your handling code here:
        try {
            String cont = JOptionPane.showInputDialog("Ingrese la contraseña:");
            if (cont.equals("unitec1234")) {
                DefaultTableModel model = (DefaultTableModel) jt_personas.getModel();
                for (int i = 0; i < personas.size(); i++) {
                    Object[] newrow = {(Object) personas.get(i).getId(), (Object) personas.get(i).getNombre(), (Object) personas.get(i).getSexo(), (Object) personas.get(i).getEstado()};
                    model.addRow(newrow);
                }
                jt_personas.setModel(model);
            } else {
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_listarpersonasMouseClicked

    private void jb_listarobjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarobjetosMouseClicked
        // TODO add your handling code here:
        try {
            String cont = JOptionPane.showInputDialog("Ingrese la contraseña:");
            if (cont.equals("unitec1234")) {
                DefaultTableModel model = (DefaultTableModel) jt_objetos.getModel();
                for (int i = 0; i < objetos.size(); i++) {
                    Object[] newrow = {(Object) objetos.get(i).getMarca(), (Object) objetos.get(i).getTamaño(), (Object) objetos.get(i).getCalidad(), (Object) objetos.get(i).getDescripcion()};
                    model.addRow(newrow);
                }
                jt_objetos.setModel(model);
            } else {
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_listarobjetosMouseClicked

    private void jb_eliminarpersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarpersMouseClicked
        // TODO add your handling code here:
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) cb_eliminarpers.getModel();
            model.removeElement(cb_eliminarpers.getSelectedItem());
            cb_eliminarpers.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_eliminarpersMouseClicked

    private void Agregar_panelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Agregar_panelStateChanged
        // TODO add your handling code here:
        try {
            if (Agregar_panel.getSelectedIndex() == 2) {
                cb_eliminarpers.addItem(personas.toString());
                cb_elimobje.addItem(objetos.toString());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Agregar_panelStateChanged

    private void jb_eliminarobjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarobjetosMouseClicked
        // TODO add your handling code here:
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) cb_elimobje.getModel();
            model.removeElement(cb_elimobje.getSelectedItem());
            cb_elimobje.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_eliminarobjetosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Agregar_panel;
    private javax.swing.JFrame Gerente;
    private javax.swing.JFrame Hogar;
    private javax.swing.JFrame Personal;
    private javax.swing.JFrame Ropa;
    private javax.swing.JFrame Zapatos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_eliminarpers;
    private javax.swing.JComboBox<String> cb_elimobje;
    private javax.swing.JComboBox<String> cb_persona;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jb_agregargerente;
    private javax.swing.JButton jb_agregarhogar;
    private javax.swing.JButton jb_agregarpersona;
    private javax.swing.JButton jb_agregarpersonal;
    private javax.swing.JButton jb_agregarropa;
    private javax.swing.JButton jb_agregarzapatos;
    private javax.swing.JButton jb_eliminarobjetos;
    private javax.swing.JButton jb_eliminarpers;
    private javax.swing.JButton jb_listarobjetos;
    private javax.swing.JButton jb_listarpersonas;
    private javax.swing.JTable jt_objetos;
    private javax.swing.JTable jt_personas;
    private javax.swing.JRadioButton rb_casado;
    private javax.swing.JRadioButton rb_femeninno;
    private javax.swing.JRadioButton rb_gerente;
    private javax.swing.JRadioButton rb_hogar;
    private javax.swing.JRadioButton rb_masculino;
    private javax.swing.JRadioButton rb_personal;
    private javax.swing.JRadioButton rb_planta;
    private javax.swing.JRadioButton rb_ropa;
    private javax.swing.JRadioButton rb_soltero;
    private javax.swing.JRadioButton rb_sucursal;
    private javax.swing.JRadioButton rb_zapatos;
    private javax.swing.JSpinner sp_calidadzapatos;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_garantiahogar;
    private javax.swing.JSpinner sp_id;
    private javax.swing.JSpinner sp_semanas;
    private javax.swing.JTextArea ta_descripcion;
    private javax.swing.JTextArea ta_descripcionhogar;
    private javax.swing.JTextArea ta_descripciono;
    private javax.swing.JTextArea ta_instruccioneshogar;
    private javax.swing.JTextField tf_altura;
    private javax.swing.JTextField tf_calidado;
    private javax.swing.JTextField tf_contraseña;
    private javax.swing.JTextField tf_horario;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_ocupacion;
    private javax.swing.JTextField tf_paisropa;
    private javax.swing.JTextField tf_peso;
    private javax.swing.JTextField tf_sueldo;
    private javax.swing.JTextField tf_tallaropa;
    private javax.swing.JTextField tf_tallazapatos;
    private javax.swing.JTextField tf_tamaño;
    private javax.swing.JTextField tf_telaropa;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
Color c;
}
